import type { FullProjectWithRelations } from "@/types";

// Standard realistic demo projects preserved for showroom display and fallback
export const DEMO_PROJECTS_DATA: FullProjectWithRelations[] = [
  {
    id: "proj_demo_math_ai",
    title: "The Math of AI",
    targetNiche: "Machine Learning & Mathematics",
    description: "Deep mathematical intuitions behind transformers, gradient descent, and neural tensor calculus.",
    isDemo: true,
    userId: null,
    createdAt: "2026-09-17T12:00:00.000Z",
    updatedAt: "2026-09-17T12:00:00.000Z",
    channelProfile: {
      id: "cp_demo_math_ai",
      projectId: "proj_demo_math_ai",
      primaryNiche: "Machine Learning Math",
      subNiches: ["Linear Algebra", "Backpropagation", "Attention Mechanisms"],
      targetAudience: "Software engineers, CS students, and AI researchers seeking rigorous geometric foundations.",
      valueProposition: "No black boxes: we derive deep neural architectures from pure first principles.",
      toneOfVoice: "Intellectual, rigorous, visual, and engaging.",
      contentPillars: ["First-Principles Proofs", "Visual Geometric Intuition", "Code-to-Math Mappings"],
      uploadSchedule: "Bi-weekly deep-dives on Thursdays",
      createdAt: "2026-09-17T12:00:00.000Z",
      updatedAt: "2026-09-17T12:00:00.000Z",
    },
    brandKit: {
      id: "bk_demo_math_ai",
      projectId: "proj_demo_math_ai",
      primaryColor: "#4F46E5",
      secondaryColor: "#06B6D4",
      accentColor: "#F59E0B",
      backgroundColor: "#0B0F17",
      headlineFont: "Plus Jakarta Sans",
      bodyFont: "JetBrains Mono",
      visualStyle: "Cyber-mathematical minimalist vector graphs",
      tagline: "Geometric intuition for deep neural networks.",
      brandPersonality: "Analytical, lucid, uncompromisingly accurate.",
      createdAt: "2026-09-17T12:00:00.000Z",
      updatedAt: "2026-09-17T12:00:00.000Z",
    },
    channelNames: [
      {
        id: "cn_demo_math_1",
        projectId: "proj_demo_math_ai",
        name: "The Math of AI",
        handle: "@TheMathOfAI",
        score: 98,
        isPrimary: true,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
      {
        id: "cn_demo_math_2",
        projectId: "proj_demo_math_ai",
        name: "Neural Intuition",
        handle: "@NeuralIntuition",
        score: 92,
        isPrimary: false,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
    ],
    assets: [
      {
        id: "asset_demo_math_banner",
        assetId: "ast_demo_math_banner",
        projectId: "proj_demo_math_ai",
        assetType: "banner",
        storageKey: "projects/proj_demo_math_ai/banner/banner.svg",
        mimeType: "image/svg+xml",
        width: 2560,
        height: 1440,
        createdAt: "2026-09-17T12:00:00.000Z",
        updatedAt: "2026-09-17T12:00:00.000Z",
      },
      {
        id: "asset_demo_math_logo",
        assetId: "ast_demo_math_logo",
        projectId: "proj_demo_math_ai",
        assetType: "logo",
        storageKey: "projects/proj_demo_math_ai/logo/logo.svg",
        mimeType: "image/svg+xml",
        width: 800,
        height: 800,
        createdAt: "2026-09-17T12:00:00.000Z",
        updatedAt: "2026-09-17T12:00:00.000Z",
      },
    ],
    keywords: [
      {
        id: "kw_demo_math_1",
        projectId: "proj_demo_math_ai",
        keyword: "transformer attention calculation math",
        searchVolume: 42000,
        competition: "Medium",
        cpc: 2.85,
        relevanceScore: 98,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
      {
        id: "kw_demo_math_2",
        projectId: "proj_demo_math_ai",
        keyword: "gradient descent multivariate calculus",
        searchVolume: 31000,
        competition: "Low",
        cpc: 1.95,
        relevanceScore: 94,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
    ],
    contentIdeas: [
      {
        id: "ci_demo_math_1",
        projectId: "proj_demo_math_ai",
        title: "How Transformers Actually Multiply Matrices (Full 3D Visual)",
        hook: "Most tutorials show Query, Key, and Value vectors as boxes. Here is what the tensor dot-product really does.",
        description: "A comprehensive derivation from soft-max scaling to multi-head aggregation.",
        format: "Deep Dive Pillar",
        targetLengthMinutes: 24,
        estimatedViews: "120K - 250K",
        difficulty: "Intermediate",
        tags: ["#DeepLearning", "#Transformers", "#LinearAlgebra"],
        isPlanned: true,
        createdAt: "2026-09-17T12:00:00.000Z",
        updatedAt: "2026-09-17T12:00:00.000Z",
      },
    ],
  },
  {
    id: "proj_demo_healthy_hub",
    title: "Healthy Living Hub",
    targetNiche: "Preventative Longevity & Nutrition",
    description: "Actionable protocols in Zone 2 cardiovascular training, circadian optimization, and micronutrient density.",
    isDemo: true,
    userId: null,
    createdAt: "2026-09-17T12:00:00.000Z",
    updatedAt: "2026-09-17T12:00:00.000Z",
    brandKit: {
      id: "bk_demo_healthy",
      projectId: "proj_demo_healthy_hub",
      primaryColor: "#059669",
      secondaryColor: "#10B981",
      accentColor: "#F59E0B",
      backgroundColor: "#064E3B",
      headlineFont: "Plus Jakarta Sans",
      bodyFont: "Inter",
      visualStyle: "Organic botanical minimalist wellness",
      tagline: "Science-backed longevity for sustained high performance.",
      createdAt: "2026-09-17T12:00:00.000Z",
      updatedAt: "2026-09-17T12:00:00.000Z",
    },
    channelNames: [
      {
        id: "cn_demo_healthy_1",
        projectId: "proj_demo_healthy_hub",
        name: "Healthy Living Hub",
        handle: "@HealthyLivingHub",
        score: 93,
        isPrimary: true,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
    ],
    contentIdeas: [],
    keywords: [],
    assets: [],
  },
  {
    id: "proj_demo_travel_limits",
    title: "Travel Without Limits",
    targetNiche: "Adventure Documentary & Remote Living",
    description: "Raw cinematic travel journals, off-grid expeditions, and sustainable digital nomad budgeting.",
    isDemo: true,
    userId: null,
    createdAt: "2026-09-17T12:00:00.000Z",
    updatedAt: "2026-09-17T12:00:00.000Z",
    brandKit: {
      id: "bk_demo_travel",
      projectId: "proj_demo_travel_limits",
      primaryColor: "#D97706",
      secondaryColor: "#EA580C",
      accentColor: "#2563EB",
      backgroundColor: "#1C1917",
      headlineFont: "Cinzel",
      bodyFont: "Inter",
      visualStyle: "National Geographic warmth and vintage film grain",
      tagline: "Wander further. Live without borders.",
      createdAt: "2026-09-17T12:00:00.000Z",
      updatedAt: "2026-09-17T12:00:00.000Z",
    },
    channelNames: [
      {
        id: "cn_demo_travel_1",
        projectId: "proj_demo_travel_limits",
        name: "Travel Without Limits",
        handle: "@TravelWithoutLimits",
        score: 96,
        isPrimary: true,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
    ],
    contentIdeas: [],
    keywords: [],
    assets: [],
  },
  {
    id: "proj_demo_ai_coding",
    title: "AI Coding Academy",
    targetNiche: "AI Engineering & Full-Stack Web",
    description: "Building production-grade SaaS, autonomous agents, and reactive web applications with cutting-edge AI.",
    isDemo: true,
    userId: null,
    createdAt: "2026-09-17T12:00:00.000Z",
    updatedAt: "2026-09-17T12:00:00.000Z",
    brandKit: {
      id: "bk_demo_coding",
      projectId: "proj_demo_ai_coding",
      primaryColor: "#3B82F6",
      secondaryColor: "#6366F1",
      accentColor: "#10B981",
      backgroundColor: "#030712",
      headlineFont: "Plus Jakarta Sans",
      bodyFont: "JetBrains Mono",
      visualStyle: "Modern developer dark theme with high contrast syntax neon",
      tagline: "Code with autonomous intelligence.",
      createdAt: "2026-09-17T12:00:00.000Z",
      updatedAt: "2026-09-17T12:00:00.000Z",
    },
    channelNames: [
      {
        id: "cn_demo_coding_1",
        projectId: "proj_demo_ai_coding",
        name: "AI Coding Academy",
        handle: "@AICodingAcademy",
        score: 97,
        isPrimary: true,
        createdAt: "2026-09-17T12:00:00.000Z",
      },
    ],
    contentIdeas: [],
    keywords: [],
    assets: [],
  },
];
